### PR TITLE
feat(template): add opencensus

### PR DESCRIPTION
**Pull request by damianopetrungaro**

### CODE REVIEW

**Comment by hexdigest** [comment]
Hi @damianopetrungaro !

Thanks for the template. Can you please provide a test for it similar to what we have for opentracing template?

**Comment by damianopetrungaro** [comment]
Sure I can, need to take a look at that.

**Comment by damianopetrungaro** [comment]
@hexdigest 👀

**Comment by hexdigest** [comment]
Thank you for this great template @damianopetrungaro !

**Comment by damianopetrungaro** [comment]
Happy to see this merged, I used it in different projects, and every time I had to refer to a private repo to get the template.

Now it's gonna be easier for the whole community to do that as well :)

**Pull request merged**
