### PR TITLE
Added TemplateInputInterface MethodsList method

### PR DESCRIPTION
**Pull request by androndo**
This method allow iterate by methods with indexes.
Use in templates example:
```
{{range $i, $method := .Interface.MethodsList}}
// something: arr[{{$i}}].Do()
{{end}}
```
Range over map not provided indexing in go templates.

### CODE REVIEW

**Comment by hexdigest** [comment]
Hi @androndo,

Can you please explain the use case for that?

**Comment by androndo** [comment]
I use this in [custom template](https://github.com/androndo/moira/pull/2/files#diff-f14eb4f3c4441cbfff8bdf6ba761f76e41767c423ab3e9b50652961c3bd1bf6eR42). This case helps to avoid intensive memory allocations for metric senders about methods duration.

**Comment by androndo** [comment]
Hi @hexdigest, what do you think about this changes?

**Comment by hexdigest** [comment]
Hey @androndo 

I don't think this method makes very much sence.
First of all you don't need an array of timers, instead you can have one timer per method. Just use method name to generate timer properties' names:
```go
struct {
  ...
  timer{{$method}} *metrics.Timer
}
```

Second thing I would suggest is to create timers in the constructor so you don't have to use mutexes and make additional checks in runtime. Btw you have a race in your template code: L34/L39

**Comment by androndo** [comment]
@hexdigest Thank for your answer :+1: Sorry, I was only able to process it today.

> you don't need an array of timers, instead you can have one timer per method

I think than I don't need all timers per methods, my idea is "lazy" creations. Because, interface contains 80+ methods, but only tiny part uses in subsystems (microservices).

> Btw you have a race in your template code: L34/L39

It's not a race it's double check.

**Comment by hexdigest** [comment]
> I think than I don't need all timers per methods, my idea is "lazy" creations. Because, interface contains 80+ methods, but only tiny part uses in subsystems (microservices).

You have problems with your interface if you have 80+ methods in it. There's "I" letter in SOLID abbreviation which stands for "Interface segregation principle". If your service doesn't use some methods it shouldn't depend on such interface. Are you familiar with duck typing in Go? You can define your own interface with the subset of methods that you really use and then you can generate decorators for YOUR interface. So there won't be any timers that are not being used. Also, lazy creations lead to sub optimal code in the places where it's really being used (you have locks, you have checks and so on)

So my recipe is:
1. Reduce your interface
2. Generate decorator using named timer per method

> > Btw you have a race in your template code: L34/L39
> It's not a race, it's a double check.

It's a race this first check is outside of the protected section:
```go
if d.timers[{{ $i }}] == nil
```

And inside the protected section you try to write to the very same slice element. So concurrent call to this code will panic time to time.

This PR won't be merged.

**Pull request closed without merging**
