### PR TITLE
feat: add template for elastic apm traces

### PR DESCRIPTION
**Pull request by gvencadze**
Adds support for Elastic APM traces.

(didn't include tests)

### CODE REVIEW

**Comment by hexdigest** [comment]
Hi @gvencadze , please take a look at this template: https://github.com/hexdigest/gowrap/blob/master/templates/elasticapm

maybe it's what you need.

**Comment by gvencadze** [comment]
@hexdigest o_O, I've created this merge request 3 week earlier.

Btw, there's a bug while call _d.captureError() - we must call Send() method to send error to APM system, otherwise it won't be sent.

**Comment by bars43ru** [comment]
by the name of the span, then I propose to do it through the opt function patter, which in turn allows you to either use the base type or set the name manually

**Comment by bars43ru** [comment]
Thanks for the note about the Send() call, I'll fix it now.

**Comment by gvencadze** [comment]
@bars43ru btw, read the docs of elastic apm please)
image

I'll suggest to avoid setting each parameter from function to labels, better add them via opt function

**Comment by bars43ru** [comment]
It looks like really use / not use 'SetLable' can be controlled through opt function. This will allow for a more general pattern.

**Comment by bars43ru** [comment]
a little later I will prepare an MR with the ability to manage the use SetLabel via opt function

**Comment by gvencadze** [comment]
@bars43ru you can tag me in MR - I've some experience with elastic apm, maybe I'll suggest anything else to make template better

**Pull request closed without merging**
