### PR TITLE
Add local export setting from goimports

### PR DESCRIPTION
**Pull request by breml**

### CODE REVIEW

**Comment by hexdigest** [comment]
Hi @breml!

Thanks for your contribution, that's a nice feature! Can you please add one test to cover it?

**Comment by breml** [comment]
Hi @hexdigest 
I am glad that you like this feature.
In regards to a test, that will cover it, I also thought about this, before I submitted the PR, but I am not exactly sure what to test.

The thing about this change is, that it does not add any new code branch. All the code is already covered by existing tests, in fact because some statements are added to already covered code branches, the over all coverage is slightly improved, because the ratio of covered to uncovered statements is increased.

All this PR does is accepting a string as flag and passing it along the call chain, until the exact same string (not verified nor altered) is assigned to the `imports.LocalPrefix` global variable of the `imports` package as well as added as output in the template for the `go:generate` template line.

I also looked at the existing tests and I could not find a similar test where the change of a particular flag is tested against the resulting output (but maybe I did not look hard enough).

Don't get me wrong, I am happy to add a test, but I was really unsure if 1. it is really needed, 2. where to add it and 3. what exactly to test.

If you provide me the necessary pointers, I am sure, I will be able to add the necessary tests.

**Comment by hexdigest** [comment]
Hey @breml, 

> Don't get me wrong, I am happy to add a test, but I was really unsure if 1. it is really needed, 2. where to add it and 3. what exactly to test. 
> If you provide me the necessary pointers, I am sure, I will be able to add the necessary tests.

Here's the right place to add such test:
https://github.com/hexdigest/gowrap/blob/master/cmd_generate_test.go#L233

You can provide a new argument and mock the writer in order to check that everything is sorted appropriately.
I was also thinking about either a shorter flag name like -l or more explicit name like -local-imports, because -local doesn't really say anything

**Comment by breml** [comment]
@hexdigest I changed the flag to `-l` as suggested by you. So far, `gowrap` only has one letter flags, so I guess it does make sense to keep it this way. Previously I did choose `-local`, because this is how the flag is named in `goimports`. So users of this feature most probably already used this flag.

I also added a test case, which does verify:

* the imports are ordered correctly
* the `go:generate` line does include the respective value for the `-l` flag

**Comment by hexdigest** [comment]
Thank you @breml! This is already available in v1.2.1 that I just released.

**Pull request merged**
